version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: meme-museum
    image: meme-museum
    volumes:
      - "./:/var/www/html"
    ports:
      - "3000:3000"
    tty: true
    env_file: .env
    environment:
      NEXT_PUBLIC_WALLETCONNECT_CHAIN_ID: "${NEXT_PUBLIC_WALLETCONNECT_CHAIN_ID}"
      NEXT_PUBLIC_WALLETCONNECT_RPC_URL: "${NEXT_PUBLIC_WALLETCONNECT_RPC_URL}"
      NEXT_PUBLIC_INFURA_ID: "${NEXT_PUBLIC_INFURA_ID}"
      WEB3STORAGE_TOKEN: "${WEB3STORAGE_TOKEN}"
      NEXT_PUBLIC_API_URL: "${NEXT_PUBLIC_API_URL}"
      PORT: "3000"
